import json
import os
import re
import string

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

GROQ_MODEL = "llama-3.1-8b-instant"

SYSTEM_PROMPT = (
    "You judge whether a piece of writing was generated by AI or written by a human. "
    "Look at tone, structure, coherence, and style. "
    "Respond with ONLY a JSON object in this exact format, no extra text: "
    '{"llm_score": 0.0, "attribution": "likely_ai"}. '
    "llm_score is a number from 0.0 to 1.0, where higher means more AI-like. "
    'attribution must be one of: "likely_ai", "likely_human", "uncertain".'
)


def analyze_with_groq(text):
    """Send text to Groq and return a dict with llm_score and attribution."""
    response = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0,
        response_format={"type": "json_object"},
    )

    raw_content = response.choices[0].message.content
    result = json.loads(raw_content)

    llm_score = float(result.get("llm_score", 0.5))
    attribution = result.get("attribution", "uncertain")

    if attribution not in ("likely_ai", "likely_human", "uncertain"):
        attribution = "uncertain"

    return {"llm_score": llm_score, "attribution": attribution}


def stylometric_score(text):
    """Score text from 0 (likely human) to 1 (likely AI) using simple writing-style stats.

    This does not call any API. It just looks at three plain-Python signals:
    - sentence length variation (humans tend to vary sentence length more)
    - vocabulary diversity (ratio of unique words to total words)
    - punctuation variety (how many different punctuation marks are used)
    """
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]
    words = [w.strip(string.punctuation).lower() for w in text.split()]
    words = [w for w in words if w]

    # 1. Sentence length variation: low variation looks more AI-like.
    sentence_lengths = [len(s.split()) for s in sentences]
    if len(sentence_lengths) > 1:
        avg_length = sum(sentence_lengths) / len(sentence_lengths)
        variance = sum((length - avg_length) ** 2 for length in sentence_lengths) / len(sentence_lengths)
        std_dev = variance ** 0.5
        variation = (std_dev / avg_length) if avg_length > 0 else 0
    else:
        variation = 0

    length_score = 1 - min(variation, 1)

    # 2. Vocabulary diversity: fewer unique words relative to total looks more AI-like.
    if words:
        vocab_diversity = len(set(words)) / len(words)
    else:
        vocab_diversity = 1

    vocab_score = 1 - vocab_diversity

    # 3. Punctuation variety: using fewer distinct punctuation marks looks more AI-like.
    punctuation_marks = set(".,;:!?-")
    used_marks = {ch for ch in text if ch in punctuation_marks}
    punctuation_variety = len(used_marks) / len(punctuation_marks)

    punctuation_score = 1 - punctuation_variety

    style_score = (length_score + vocab_score + punctuation_score) / 3

    return max(0.0, min(1.0, style_score))


def combine_scores(llm_score, style_score):
    """Combine the two signals into one score, weighted toward the LLM signal."""
    return 0.6 * llm_score + 0.4 * style_score


def score_to_attribution(combined_score):
    """Turn a combined score into a human-readable attribution label."""
    if combined_score >= 0.75:
        return "likely_ai"
    if combined_score >= 0.40:
        return "uncertain"
    return "likely_human"


def detect(text):
    """Run both detection signals on text and return the combined result."""
    groq_result = analyze_with_groq(text)
    llm_score = groq_result["llm_score"]

    style_score = stylometric_score(text)

    confidence = combine_scores(llm_score, style_score)
    attribution = score_to_attribution(confidence)

    return {
        "llm_score": llm_score,
        "style_score": style_score,
        "confidence": confidence,
        "attribution": attribution,
    }
